### ISSUE TITLE
[FEATURE] Logback 모니터링

### ISSUE THREAD

**Issue by hyunmin0317** [smu-nity/smunity-infra#3]
## 상세 기능

- `logback-spring.xml` 설정을 통해 스프링 연동
- Loki 를 통해 로그 수집 및 분석
- Grafana 를 통한 로그 데이터 시각화

**Comment by hyunmin0317** [comment]
## 관련자료
- https://velog.io/@roycewon/Promtail-Loki%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%9C-Logback-%EB%AA%A8%EB%8B%88%ED%84%B0%EB%A7%81
- https://velog.io/@stella6767/%EB%AA%A8%EB%8B%88%ED%84%B0%EB%A7%81-%EC%84%9C%EB%B2%84-%EA%B5%AC%EC%B6%95-feat.-Grafana-Loki-Promtail

**Comment by jinho7** [comment]
모니터링 툴 공부 GOOD
